### ISSUE TITLE
custom db_sql class does not use parameterisation

### ISSUE THREAD

**Issue by danmarsden** [SE-Stuttgart/kib3_moodleplugin_srg#12]
Moodle's Data manipulation API provides SQL injection protection using placeholders to facilitate secure and cross-database compatible code.

Your [db_sql class wrapper ](https://github.com/SE-Stuttgart/moodle-mod_srg/blob/main/classes/db_conn/db_sql.php)bypasses this protection - typically you should not wrap these apis in a wrapper, but should exclusively use the functions directly with correct use of placeholders.

Looking at your current usage of the wrapper, I see that the values passed to your wrapper are the $USER global and a $course object returned from a Moodle database call, but this wrapper is a significant deviation on the standard use of Moodle apis and typically when variables are injected into inline SQL queries we'd block approval in the plugins database until this is addressed.

I'll raise it internally here with the other plugin review team members but we may need you to clean this up before we can approve this plugin.

more information on this is here:
https://moodledev.io/general/community/plugincontribution/checklist#security

and the main api is documented here:
https://moodledev.io/docs/apis/core/dml

**Comment by mudrd8mz** [comment]
+1 to what Dan says.

More than that, I noticed double quotes used in the SQL fragments in your wrapper. From what I recall, these did not work well in PostgreSQL -- double quotes in PostgreSQL are used to indicate identifiers within the database such as column names. So things like https://github.com/SE-Stuttgart/moodle-mod_srg/blob/0490015039a4ba7c7e0a7ebb2721b3ef60044427/classes/db_conn/db_sql.php#L122 are likely to not work cross-DB.
