### ISSUE TITLE
consider adding github actions support - it's free and very useful.

### ISSUE THREAD

**Issue by danmarsden** [SE-Stuttgart/kib3_moodleplugin_srg#5]
Some of the tests run by the Moodle.org plugins db can be run via github actions on each commit in your github repo. Enabling this helps you to make sure future changes to your plugin will continue to follow the guidelines.

the short version - grab this file:
https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml
rename it as ci.yml and put into the directory .github/workflows within tyour project eg:
https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_311_STABLE/.github/workflows/ci.yml

then on every commit you make to github it will fire off a request to run the tests and will give you traffic lights beside each commit and generate a report.

**Comment by MakinZeel** [comment]
Thanks for the feedback.
I used your suggested files but I am irritated by one flag: It say's that the defined('MOODLE_INTERNAL') || die(); is not necessary in the lib.php but for me it seems customary to have it (all default activities I found have it). (I currently don't have it.

**Comment by danmarsden** [comment]
Hi @MakinZeel yes - there's some inconsistency with that variable across various plugins which is the reason it was added as a new rule to the codechecker - please note that you do not have to fix all the issues reported by the codechecker for plugins db approval - it's just a nice to have as the plugins db also shows a little "code prechecks" status below the download button that shows how many errors/warnings are present in the plugin version and it's a nice indicator of how well your plugin follows standard guidelines.

The moodle_internal check is intended to be used on files that contain in-line PHP code - files that only contain functions or classes don't need it.
